/**
 * Rate AI — Offline sample data & Canonical AI Tool Records
 *
 * Loaded in sample-data mode (?mock=1) and used by the static tool page generator.
 * Contains high-ranking Google SEO titles, meta descriptions, target tags, and
 * Play Store-grade specifications and data safety declarations.
 */

export const MOCK_TOOLS = [
  {
    docId: 'chatgpt.com',
    domain: 'chatgpt.com',
    name: 'ChatGPT',
    seoTitle: 'ChatGPT: Get instant answers, find inspiration, learn something new',
    metaDescription: 'ChatGPT is a free-to-use AI system. Use it for engaging conversations, gain insights, automate tasks, and witness the future of AI, all in one place.',
    seoKeywords: ['ai chat', 'conversational ai', 'gpt-4o', 'openai', 'artificial intelligence', 'prompt engineering', 'writing assistant', 'reasoning model'],
    howItWorks: 'Built on OpenAI’s Generative Pre-trained Transformer (GPT-4o) architecture with Reinforcement Learning from Human Feedback (RLHF). Processes multimodal prompts across text, vision, and audio with integrated code execution sandboxes and real-time internet search.',
    downloadsOrUsers: '180M+ Monthly Users',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['Web', 'iOS', 'Android', 'macOS', 'Windows', 'API'],
    category: 'Chatbot',
    company: 'OpenAI',
    website: 'https://chatgpt.com',
    pricing: ['Freemium'],
    avgRating: 4.88,
    totalRatings: 48200,
    totalReviews: 3120,
    ratingDistribution: { 1: 1200, 2: 2100, 3: 6400, 4: 15600, 5: 22900 },
    verified: true,
    founded: 2022,
    twitter: '@OpenAI',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Introduced GPT-4o with real-time Advanced Voice Mode, faster image processing, and custom memory retention controls.',
    dataSafety: {
      encryption: 'Data encrypted in transit via TLS 1.3 and at rest with AES-256',
      training: 'User inputs can be excluded from model training via Privacy Settings',
      compliance: 'SOC 2 Type II, GDPR, CCPA, ISO/IEC 27001 compliant',
      retention: 'Conversation history can be permanently deleted with instant export',
    },
    screenshots: [
      { title: 'Multimodal Chat', caption: 'Natural language conversations with instant web search citations and file analysis' },
      { title: 'Advanced Voice', caption: 'Fluid real-time voice mode with human-like intonation and natural interruptions' },
      { title: 'Data Analysis', caption: 'Python code execution sandbox for plotting charts, spreadsheets, and statistical models' },
      { title: 'Custom GPTs', caption: 'Specialized tailored assistants configured for specific workflows, coding, and writing' },
    ],
    features: [
      'Multimodal input supporting conversational text, voice, files, and vision',
      'Real-time live web browsing and verifiable source citations',
      'Advanced data analysis with automated Python code execution',
      'Custom GPT marketplace and collaborative workspace teams',
      'Voice mode with human-like cadences and dynamic interruption',
    ],
    useCases: [
      'Everyday problem-solving, brainstorming, and research synthesis',
      'Complex data spreadsheet cleaning and interactive chart generation',
      'Multilingual translation, language tutoring, and email drafting',
    ],
    pros: [
      'Versatile performance across almost every technical and creative domain',
      'Extremely generous free access tier with GPT-4o mini',
      'Fast, low-latency responses with memory for continuing discussions',
    ],
    cons: [
      'Requires Pro tier for peak compute hours and high o1 reasoning limits',
      'Occasional hallucinations on obscure historical or niche technical trivia',
    ],
  },
  {
    docId: 'claude.ai',
    domain: 'claude.ai',
    name: 'Claude',
    seoTitle: 'The AI for Problem Solvers | Claude by Anthropic',
    metaDescription: 'Claude is a next-generation AI assistant based on Anthropic’s research into training helpful, honest, and harmless AI systems with industry-leading context windows.',
    seoKeywords: ['claude ai', 'anthropic', 'claude 3.5 sonnet', 'safe ai', 'long context window', 'coding assistant', 'document analysis', 'constitutional ai'],
    howItWorks: 'Trained using Constitutional AI principles and hybrid Transformer architectures. Features a 200,000+ token context window capable of ingesting entire code repositories, financial filings, and research papers with near-zero hallucination.',
    downloadsOrUsers: '25M+ Active Users',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['Web', 'iOS', 'Android', 'macOS', 'API'],
    category: 'Chatbot',
    company: 'Anthropic',
    website: 'https://claude.ai',
    pricing: ['Freemium'],
    avgRating: 4.92,
    totalRatings: 18420,
    totalReviews: 1240,
    ratingDistribution: { 1: 210, 2: 340, 3: 1120, 4: 4180, 5: 12570 },
    verified: true,
    founded: 2021,
    twitter: '@AnthropicAI',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Claude 3.5 Sonnet release featuring interactive Artifacts, vision reasoning, and upgraded coding benchmarks.',
    dataSafety: {
      encryption: 'TLS 1.3 in transit and AES-256 at rest',
      training: 'Anthropic does not train commercial models on customer conversation prompts',
      compliance: 'SOC 2 Type II, HIPAA eligible, GDPR compliant',
      retention: 'Data retained only per enterprise configuration, with 30-day deletion defaults',
    },
    screenshots: [
      { title: 'Interactive Artifacts', caption: 'Side-by-side live UI rendering for React, HTML, SVG diagrams, and markdown' },
      { title: 'Long Document Analysis', caption: 'Ingest 200k+ tokens of legal contracts, RFCs, and books in a single prompt' },
      { title: 'Code Intelligence', caption: 'State-of-the-art software architecture planning, bug fixing, and unit test drafting' },
      { title: 'Project Knowledge', caption: 'Custom persistent document context pinned to dedicated workspace projects' },
    ],
    features: [
      '200,000+ token context window for comprehensive book-length document ingestion',
      'Artifacts interface displaying live interactive code, SVG diagrams, and web apps',
      'State-of-the-art programming, code generation, and logical reasoning benchmarks',
      'Prompt caching technology reducing latency and cost on repeated references',
    ],
    useCases: [
      'Complex contract and legal brief summarization and discrepancy analysis',
      'Software architectural planning and multi-file code refactoring',
      'In-depth academic literature reviews and grant proposal drafting',
    ],
    pros: [
      'Exceptional nuanced long-form prose quality with thoughtful structure',
      'Industry-leading context retention across extended multi-turn sessions',
      'Interactive Artifacts provide live visual execution for frontends and diagrams',
    ],
    cons: [
      'Refusal safety filters can trigger on sensitive creative edge prompts',
      'Standard tier lacks real-time search engine browsing',
    ],
  },
  {
    docId: 'cursor.com',
    domain: 'cursor.com',
    name: 'Cursor',
    seoTitle: 'Build Software with AI Agents - Cursor AI Code Editor',
    metaDescription: 'Cursor plans, writes, and reviews code using AI agents that understand your entire codebase. Everywhere you work: Desktop, CLI, Web & Mobile.',
    seoKeywords: ['ai code editor', 'cursor ide', 'ai pair programmer', 'copilot alternative', 'codebase indexing', 'semantic code search', 'multi-file edit'],
    howItWorks: 'A native fork of Visual Studio Code engineered with local vector embeddings and semantic codebase indexing. Cursor uses agentic multi-model pipelines (Claude 3.5 Sonnet, GPT-4o) to plan, generate multi-file diffs, and inspect terminal outputs in real time.',
    downloadsOrUsers: '1M+ Developers',
    contentRating: 'Developer & Enterprise Ready',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['macOS', 'Windows', 'Linux', 'CLI'],
    category: 'Coding',
    company: 'Anysphere',
    website: 'https://cursor.com',
    pricing: ['Freemium', 'Paid'],
    avgRating: 4.86,
    totalRatings: 12880,
    totalReviews: 910,
    ratingDistribution: { 1: 180, 2: 300, 3: 980, 4: 3600, 5: 7820 },
    verified: true,
    founded: 2022,
    twitter: '@cursor_run',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Added Composer multi-file agent mode, background codebase re-indexing, and custom .cursorrules file support.',
    dataSafety: {
      encryption: 'End-to-end TLS 1.3 encryption; Privacy Mode ensures code is never stored or trained on',
      training: 'Zero code retention mode available for all individual and enterprise accounts',
      compliance: 'SOC 2 Type II certified',
      retention: 'Code embeddings stored locally on machine or in ephemeral encrypted cache',
    },
    screenshots: [
      { title: 'Composer Multi-file Agent', caption: 'Instruct AI to orchestrate cross-file refactors with visual interactive diffs' },
      { title: 'Codebase @-Mentions', caption: 'Query files, git commits, documentation, and web pages directly in chat' },
      { title: 'Predictive Tab Completion', caption: 'Multi-line intelligent autocomplete anticipating your next edit before you type' },
      { title: 'Terminal Debugging', caption: 'Instant error diagnosis and auto-fix proposals for failing commands and test suites' },
    ],
    features: [
      'Repository-wide codebase indexing and instant semantic code search',
      'Multi-file inline Composer editing with visual unified diff previews',
      'Custom repository rules and team conventions configured via .cursorrules',
      'Zero-latency model toggle between Claude 3.5 Sonnet and GPT-4o',
    ],
    useCases: [
      'Full-stack migrations and cross-file API refactoring across large repos',
      'Automated test suite generation from production codebases',
      'Rapidly navigating and understanding unfamiliar open-source projects',
    ],
    pros: [
      'Understands multi-file dependencies and repository architecture natively',
      'Preserves your entire VS Code extension library, settings, and keybindings',
      'Fast inline acceptance, rejection, and review controls for proposed diffs',
    ],
    cons: [
      'High memory usage on massive monorepos with hundreds of thousands of files',
      'Pro plan required for continuous heavy daily Fast-request quotas',
    ],
  },
  {
    docId: 'midjourney.com',
    domain: 'midjourney.com',
    name: 'Midjourney',
    seoTitle: 'Midjourney - AI Art Generator & Creative Imaging',
    metaDescription: 'Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species through state-of-the-art diffusion models.',
    seoKeywords: ['ai art generator', 'midjourney v6', 'text to image', 'photorealistic ai', 'generative art', 'digital illustration', 'prompt crafting'],
    howItWorks: 'Operates proprietary latent diffusion algorithms optimized for cinematic aesthetics, nuanced lighting, and photorealism. Interprets complex natural language prompts with fine-grained control parameters (--ar, --stylize, --sref, --cref) to synthesize high-resolution imagery.',
    downloadsOrUsers: '20M+ Creators',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['Web', 'Discord'],
    category: 'Image',
    company: 'Midjourney',
    website: 'https://midjourney.com',
    pricing: ['Paid'],
    avgRating: 4.81,
    totalRatings: 22140,
    totalReviews: 1580,
    ratingDistribution: { 1: 420, 2: 780, 3: 2640, 4: 7100, 5: 11200 },
    verified: true,
    founded: 2021,
    twitter: '@midjourney',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Midjourney v6.1 released with improved hand rendering, photorealistic skin textures, and dedicated web creation canvas.',
    dataSafety: {
      encryption: 'Standard TLS 1.3 transport encryption and secure cloud asset storage',
      training: 'Models trained on public and curated visual datasets',
      compliance: 'Terms of Service enforce strict anti-deepfake and community safety guidelines',
      retention: 'Private Stealth generation available for Pro and Mega subscribers',
    },
    screenshots: [
      { title: 'Web Creation Canvas', caption: 'Direct browser generation with intuitive sliders for stylization, speed, and aspect ratio' },
      { title: 'Inpainting & Region Variation', caption: 'Selectively erase and repaint specific canvas zones with targeted text prompts' },
      { title: 'Style Reference (--sref)', caption: 'Lock exact visual aesthetics and color palettes across multiple generated scenes' },
      { title: 'Character Reference (--cref)', caption: 'Maintain identical face and costume consistency across storyboards' },
    ],
    features: [
      'Unsurpassed aesthetic quality, photorealistic lighting, and atmospheric depth',
      'Web-based generation interface alongside classic Discord bot pipelines',
      'Style reference (--sref) and Character reference (--cref) consistency parameters',
      'Interactive Vary Region canvas for inpainting, zoom-out, and outpainting',
    ],
    useCases: [
      'Cinematic concept art and moodboarding for games, films, and advertising',
      'High-fashion, architectural visualization, and portrait exploration',
      'Graphic design backgrounds, album artwork, and editorial book illustrations',
    ],
    pros: [
      'World-class aesthetic polish right out of the box with minimal prompt hacking',
      'Active global community with rich public prompt galleries for inspiration',
      'Continuous model refinements with major fidelity improvements each quarter',
    ],
    cons: [
      'No free tier available; requires monthly paid subscription',
      'Precise text rendering within complex image layouts can still require iterations',
    ],
  },
  {
    docId: 'elevenlabs.io',
    domain: 'elevenlabs.io',
    name: 'ElevenLabs',
    seoTitle: 'ElevenLabs: Free AI Voice Generator & Voice Agents Platform',
    metaDescription: 'Create lifelike speech with our AI voice generator and voice agents platform. Access 5000+ voices in 70+ languages with secure APIs and SDKs.',
    seoKeywords: ['ai voice generator', 'text to speech', 'voice cloning', 'elevenlabs api', 'voice agents', 'multilingual speech synthesis', 'dubbing', 'audio ai'],
    howItWorks: 'Leverages deep generative audio networks that capture human emotional cadences, breathing patterns, and vocal inflections. Provides instant zero-shot voice cloning from 60 seconds of audio, multi-speaker dubbing in 70+ languages, and ultra-low latency streaming voice agents.',
    downloadsOrUsers: '5M+ Voice Creators',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'New York, NY, USA / London, UK',
    platforms: ['Web', 'iOS', 'Android', 'API', 'SDK'],
    category: 'Audio',
    company: 'ElevenLabs',
    website: 'https://elevenlabs.io',
    pricing: ['Freemium', 'Paid'],
    avgRating: 4.84,
    totalRatings: 7120,
    totalReviews: 480,
    ratingDistribution: { 1: 110, 2: 200, 3: 640, 4: 2000, 5: 4170 },
    verified: true,
    founded: 2022,
    twitter: '@elevenlabsio',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Launched Conversational AI Voice Agents platform with sub-400ms latency and multilingual voice-to-voice streaming.',
    dataSafety: {
      encryption: 'Encrypted with TLS 1.3 and AES-256; Voice Captcha prevents unauthorized cloning',
      training: 'Custom voices are private by default and excluded from general model training',
      compliance: 'SOC 2 Type II certified and GDPR compliant',
      retention: 'Generated audio files can be downloaded and purged anytime',
    },
    screenshots: [
      { title: 'Text to Speech Studio', caption: 'Fine-tune emotion, stability, and style exaggeration with real-time waveform preview' },
      { title: 'Voice Cloning Lab', caption: 'Instant and professional voice cloning with strict biometric safety verification' },
      { title: 'AI Dubbing Studio', caption: 'Translate videos into 70+ languages while preserving original speaker vocal tone' },
      { title: 'Voice Agents Platform', caption: 'Deploy low-latency conversational phone and web agents with custom LLM backends' },
    ],
    features: [
      'Instant voice cloning from short audio clips and professional studio cloning',
      'Text-to-speech with granular emotional inflections, pause timing, and pitch controls',
      'Automated video dubbing studio with synchronized lip movement in 70+ languages',
      'Low-latency WebSocket streaming API for real-time interactive voice agents',
    ],
    useCases: [
      'Commercial audiobook narration and episodic podcast voiceover production',
      'Multilingual video game character dialogue with expressive emotional range',
      'Customer support voice agents for real-time automated phone inquiries',
    ],
    pros: [
      'Most realistic human cadence, breathing rhythm, and prosody in synthetic audio',
      'Massive community voice library with thousands of verified regional accents',
      'Comprehensive developer SDKs across Python, JavaScript, and REST APIs',
    ],
    cons: [
      'Monthly character quotas can deplete quickly when producing long audiobooks',
      'Identity verification required for cloning real individual human voices',
    ],
  },
  {
    docId: 'perplexity.ai',
    domain: 'perplexity.ai',
    name: 'Perplexity',
    seoTitle: 'Perplexity Search | Accurate, Cited AI Answers for Every Question',
    metaDescription: 'Perplexity is a free AI-powered answer engine that provides accurate, trusted, and real-time answers to any question with verifiable sources.',
    seoKeywords: ['ai search engine', 'perplexity ai', 'answer engine', 'real time web search', 'cited sources', 'research assistant', 'copilot search'],
    howItWorks: 'Combines live multi-source web indexing, Retrieval-Augmented Generation (RAG), and top foundation models (Claude 3.5 Sonnet, GPT-4o). Dynamically synthesizes concise answers accompanied by numbered inline citations pointing to authoritative source domains.',
    downloadsOrUsers: '15M+ Monthly Researchers',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['Web', 'iOS', 'Android', 'Chrome Extension', 'API'],
    category: 'Search',
    company: 'Perplexity AI',
    website: 'https://perplexity.ai',
    pricing: ['Freemium'],
    avgRating: 4.79,
    totalRatings: 9640,
    totalReviews: 720,
    ratingDistribution: { 1: 240, 2: 420, 3: 1380, 4: 3200, 5: 4400 },
    verified: true,
    founded: 2022,
    twitter: '@perplexity_ai',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Added Perplexity Pages for publishing formatted research dossiers and introduced Spaces for collaborative team dossiers.',
    dataSafety: {
      encryption: 'All web queries encrypted over TLS 1.3; enterprise accounts guarantee non-retention',
      training: 'Pro and Enterprise users can toggle off search history training',
      compliance: 'SOC 2 Type II and GDPR compliant',
      retention: 'Search thread history can be cleared, exported, or organized in private collections',
    },
    screenshots: [
      { title: 'Interactive Answer Engine', caption: 'Comprehensive prose answers with clickable numbered citations for every factual claim' },
      { title: 'Pro Guided Search', caption: 'Interactive clarification prompts that narrow down complex queries before searching' },
      { title: 'Focus Modes', caption: 'Filter search scope specifically across Academic papers, YouTube, Reddit, or Finance' },
      { title: 'Perplexity Pages', caption: 'Convert comprehensive research threads into clean, publishable web articles' },
    ],
    features: [
      'Real-time live web indexing delivering verifiable, numbered inline citations',
      'Focus modes for targeting Academic papers, YouTube, Reddit, and financial data',
      'Spaces for organizing collaborative research dossiers with custom system prompts',
      'Instant model switching between Claude 3.5 Sonnet, GPT-4o, and Sonar',
    ],
    useCases: [
      'Market research, competitor analysis, and financial due diligence',
      'Fact-checking breaking technical news and finding primary authoritative sources',
      'Academic background research with direct paper and PDF citations',
    ],
    pros: [
      'Direct link citations verify every substantive claim, eliminating guesswork',
      'Completely ad-free, clutter-free research environment that respects time',
      'First-class mobile apps for iOS and Android with fast voice input search',
    ],
    cons: [
      'May occasionally cite secondary blogs or paywalled articles without full access',
      'Pro searches have hourly query quotas on the most powerful model tiers',
    ],
  },
  {
    docId: 'github.com',
    domain: 'github.com',
    name: 'GitHub Copilot',
    seoTitle: 'GitHub Copilot · Your AI pair programmer · GitHub',
    metaDescription: 'GitHub Copilot is an AI coding assistant that helps you write code faster and with less effort directly inside your favorite IDE.',
    seoKeywords: ['github copilot', 'ai pair programmer', 'code completion', 'visual studio code', 'inline suggestions', 'unit test generator', 'developer productivity'],
    howItWorks: 'Deeply integrated into modern IDEs (VS Code, JetBrains, Visual Studio, Neovim) using language server protocols and OpenAI models. Analyzes open editor tabs, function signatures, comments, and project context to deliver sub-second inline completions and conversational assistance.',
    downloadsOrUsers: '50M+ Developers',
    contentRating: 'Enterprise Ready',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['VS Code', 'JetBrains', 'Visual Studio', 'Neovim', 'GitHub.com', 'CLI'],
    category: 'Coding',
    company: 'GitHub / Microsoft',
    website: 'https://github.com/features/copilot',
    pricing: ['Paid'],
    avgRating: 4.74,
    totalRatings: 31400,
    totalReviews: 2040,
    ratingDistribution: { 1: 900, 2: 1800, 3: 5200, 4: 11400, 5: 12100 },
    verified: true,
    founded: 2021,
    twitter: '@github',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Added Copilot Workspace for specification-to-code planning and multi-model support in VS Code Chat.',
    dataSafety: {
      encryption: 'Enterprise TLS 1.3; Microsoft Azure sovereign security framework',
      training: 'Copilot Business and Enterprise do not retain or train on proprietary code snippets',
      compliance: 'SOC 1/2/3, ISO 27001, GDPR, FedRAMP High compliant',
      retention: 'Zero code retention policy with public code match blocking filters',
    },
    screenshots: [
      { title: 'Sub-second Ghost Text', caption: 'Intelligent multi-line inline completions suggesting whole functions as you type' },
      { title: 'Copilot Chat in IDE', caption: 'Interactive sidebar explaining code, generating tests, and fixing bugs inline' },
      { title: 'Pull Request Summaries', caption: 'Auto-generate descriptive pull request titles, summaries, and impact notes' },
      { title: 'Copilot in CLI', caption: 'Natural language terminal assistant translating queries into exact shell commands' },
    ],
    features: [
      'Sub-second ghost-text tab completions that predict next lines and logic blocks',
      'Interactive chat sidebar integrated with VS Code, JetBrains, Visual Studio, and Neovim',
      'Automated Pull Request description generator and vulnerability security scanner',
      'Commercial intellectual property indemnification and copyright match filters',
    ],
    useCases: [
      'Automating repetitive boilerplate functions, schema types, and CRUD operations',
      'Generating comprehensive unit test fixtures and mock datasets in seconds',
      'Quickly understanding legacy unfamiliar codebases and complex algorithms',
    ],
    pros: [
      'Lowest latency inline completion of any AI developer tool on the market',
      'Backed by official Microsoft enterprise compliance and central seat management',
      'Broad compatibility across all major programming languages and editor environments',
    ],
    cons: [
      'Chat assistant is slower than specialized agents for large multi-file refactors',
      'No permanent free tier available for professional individual developers',
    ],
  },
  {
    docId: 'runwayml.com',
    domain: 'runwayml.com',
    name: 'Runway',
    seoTitle: 'Runway ML · Generative AI Video, Tools & Research',
    metaDescription: 'Runway is an applied AI research company shaping the next era of art, entertainment and human creativity with state-of-the-art video generation (Gen-3 Alpha).',
    seoKeywords: ['ai video generator', 'gen-3 alpha', 'runwayml', 'text to video', 'video to video', 'camera control', 'motion brush', 'generative filmmaking'],
    howItWorks: 'Pioneered spatial-temporal video diffusion architectures (Gen-2, Gen-3 Alpha) modeling physics, lighting, and camera motion over time. Converts natural language prompts and reference imagery into cinematic 4K video clips with director-level motion controls.',
    downloadsOrUsers: '10M+ Filmmakers & Creators',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'New York, NY, USA',
    platforms: ['Web', 'iOS', 'API'],
    category: 'Video',
    company: 'Runway',
    website: 'https://runwayml.com',
    pricing: ['Freemium', 'Paid'],
    avgRating: 4.62,
    totalRatings: 5340,
    totalReviews: 360,
    ratingDistribution: { 1: 220, 2: 400, 3: 1100, 4: 1720, 5: 1900 },
    verified: true,
    founded: 2018,
    twitter: '@runwayml',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Gen-3 Alpha Turbo released with 7x faster generation speeds and advanced camera pan/tilt controls.',
    dataSafety: {
      encryption: 'Encrypted over TLS 1.3 with secure cloud video rendering clusters',
      training: 'Trained on proprietary curated visual datasets; user footage protected by privacy policy',
      compliance: 'SOC 2 compliant and GDPR compliant',
      retention: 'Full control over project asset libraries with manual and bulk deletion',
    },
    screenshots: [
      { title: 'Gen-3 Alpha Video Engine', caption: 'High-definition text-to-video and image-to-video generation with realistic physics' },
      { title: 'Director Camera Controls', caption: 'Precise cinematic trajectory controls including orbit, crane, pan, and zoom' },
      { title: 'Motion Brush', caption: 'Paint selective regions of any still image to animate water, smoke, fire, or characters' },
      { title: 'In-Browser Timeline Editor', caption: 'Assemble, trim, and composite multiple AI clips on a standard multi-track timeline' },
    ],
    features: [
      'Gen-3 Alpha high-definition text-to-video and image-to-video generation models',
      'Cinematic camera trajectory controls including pan, tilt, zoom, dolly, and roll',
      'Interactive Motion Brush for animating selective pixel zones on still photos',
      'Full in-browser multi-track video editor with green screen and inpainting tools',
    ],
    useCases: [
      'Cinematic commercial B-roll, music video transitions, and visual visual effects',
      'Film pre-visualization, commercial treatments, and animated storyboarding',
      'Social media promotional video assets and dynamic motion graphics',
    ],
    pros: [
      'High cinematic resolution, realistic camera motion, and photorealistic lighting',
      'Precise motion brush gives fine control over which elements in a scene animate',
      'Rapid release cadence with state-of-the-art updates every few months',
    ],
    cons: [
      'Generation credits deplete rapidly when exploring multiple creative concepts',
      'Complex fast-moving human anatomy can occasionally exhibit warping artifacts',
    ],
  },
  {
    docId: 'notion.so',
    domain: 'notion.so',
    name: 'Notion AI',
    seoTitle: 'Meet your AI team | Notion AI Connected Workspace',
    metaDescription: 'Notion AI is your built-in teammate inside Notion, working directly in your pages, docs, tasks, and databases so you can move faster without switching tools.',
    seoKeywords: ['notion ai', 'ai workspace', 'automated meeting notes', 'ai doc writer', 'database autofill', 'enterprise search', 'connected workspace'],
    howItWorks: 'Deeply integrated into Notion’s structured block architecture. Operates cross-workspace semantic search and LLMs to synthesize answers across docs, Slack, and Google Drive, write content, extract action items, and automatically populate database properties.',
    downloadsOrUsers: '35M+ Knowledge Workers',
    contentRating: 'Enterprise Ready',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['Web', 'macOS', 'Windows', 'iOS', 'Android'],
    category: 'Productivity',
    company: 'Notion',
    website: 'https://notion.so/product/ai',
    pricing: ['Paid'],
    avgRating: 4.58,
    totalRatings: 14200,
    totalReviews: 980,
    ratingDistribution: { 1: 800, 2: 1400, 3: 3800, 4: 4600, 5: 3600 },
    verified: true,
    founded: 2016,
    twitter: '@NotionHQ',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Added Notion AI Q&A with connectors to Google Drive and Slack, plus automated database column autofill.',
    dataSafety: {
      encryption: 'TLS 1.3 in transit and AES-256 at rest; strict workspace permission isolation',
      training: 'Customer data is never used to train foundational AI models without consent',
      compliance: 'SOC 2 Type II, ISO 27001, GDPR, HIPAA compliant',
      retention: 'Data retention respects Notion workspace policies and user permission boundaries',
    },
    screenshots: [
      { title: 'Universal Workspace Q&A', caption: 'Ask questions across your entire company Notion wiki, docs, and linked tools' },
      { title: 'Inline Writing Assistant', caption: 'Brainstorm, edit, rewrite, and summarize text directly within the page editor' },
      { title: 'Database Autofill', caption: 'Automatically extract tags, summaries, and action items across database rows' },
      { title: 'Meeting Note Extraction', caption: 'Turn messy meeting transcripts into structured action items and follow-ups' },
    ],
    features: [
      'Universal Q&A searching across Notion pages, Slack channels, and Google Drive docs',
      'Inline writing assistant with tone adjustment, proofreading, and translation',
      'Database autofill that parses row content to generate summary and tag properties',
      'Automated meeting transcript parsing and structured action item generation',
    ],
    useCases: [
      'Instantly finding project specifications and decisions buried in past team notes',
      'Transforming rough brainstorming bullet points into polished PRDs and briefs',
      'Automating classification and summarization across large corporate project trackers',
    ],
    pros: [
      'Zero copy-pasting required; operates seamlessly right where your work lives',
      'Respects all existing Notion page permissions and team privacy boundaries',
      'Eliminates hours of tedious manual database tagging and documentation reviews',
    ],
    cons: [
      'Available only as a paid monthly add-on per workspace member',
      'Output accuracy depends heavily on how up-to-date your team documentation is',
    ],
  },
  {
    docId: 'v0.dev',
    domain: 'v0.dev',
    name: 'v0',
    seoTitle: 'v0 by Vercel – Generative UI & Full-Stack AI Assistant',
    metaDescription: 'Your collaborative AI assistant to design, iterate, and scale full-stack applications for the web with React, Tailwind CSS, and shadcn/ui.',
    seoKeywords: ['generative ui', 'v0 vercel', 'ai website builder', 'react component generator', 'shadcn ui', 'prompt to website', 'full stack ai'],
    howItWorks: 'Generative UI system engineered specifically on clean React, Next.js App Router, Tailwind CSS, and shadcn/ui. Converts natural language prompts and image mockups into accessible, copy-pasteable frontend components with live sandbox previews.',
    downloadsOrUsers: '2M+ Frontend Developers',
    contentRating: 'Developer & Enterprise Ready',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['Web', 'CLI'],
    category: 'Coding',
    company: 'Vercel',
    website: 'https://v0.dev',
    pricing: ['Freemium'],
    avgRating: 4.67,
    totalRatings: 2840,
    totalReviews: 180,
    ratingDistribution: { 1: 140, 2: 260, 3: 640, 4: 900, 5: 900 },
    verified: true,
    founded: 2023,
    twitter: '@v0',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Added full-stack Next.js project generation, direct GitHub repository push, and custom theme presets.',
    dataSafety: {
      encryption: 'TLS 1.3 encryption across all generations; Vercel enterprise infrastructure',
      training: 'User generations in private projects are protected and not trained upon',
      compliance: 'SOC 2 Type II and GDPR compliant',
      retention: 'Generations can be kept private, shared via unlisted link, or deleted permanently',
    },
    screenshots: [
      { title: 'Prompt to React UI', caption: 'Generate production-ready React components with clean Tailwind CSS from text prompts' },
      { title: 'Interactive Sandbox Preview', caption: 'Test responsive breakpoints, mobile viewports, and component states in real time' },
      { title: 'Section-by-Section Iteration', caption: 'Click any specific element in the generated UI to request targeted revisions' },
      { title: 'One-Click Deploy & npx', caption: 'Directly copy component code or add to your repo using npx v0 add' },
    ],
    features: [
      'Generates accessible React, Next.js, and shadcn/ui components from descriptions',
      'Interactive visual preview sandbox with responsive mobile and desktop breakpoint testing',
      'Copy-paste component code or inject directly into projects via npx command',
      'Fine-grained conversational iteration for refining specific UI sections and colors',
    ],
    useCases: [
      'Rapidly creating frontend dashboard prototypes, landing pages, and web forms',
      'Generating responsive pricing tables, navigation bars, and authentication modals',
      'Exploring design system variations and themes for new web applications',
    ],
    pros: [
      'Produces clean, production-grade Tailwind CSS markup matching industry best practices',
      'Tight integration with Vercel hosting, shadcn/ui library, and Lucide icons',
      'Real-time interactive preview sandbox significantly accelerates UI prototyping',
    ],
    cons: [
      'Complex backend business logic and database models must still be implemented manually',
      'Free generation credits can be used up quickly during extensive design iterations',
    ],
  },
  {
    docId: 'figma.com',
    domain: 'figma.com',
    name: 'Figma AI',
    seoTitle: 'Figma AI: Smart Design Tools for Modern Teams',
    metaDescription: 'Supercharge your creative workflow with generative design, layer organization, and instant visual mockups directly inside Figma.',
    seoKeywords: ['figma ai', 'ai design tool', 'ui design generator', 'auto layout ai', 'figma plugins', 'vector ai'],
    howItWorks: 'Embedded directly within Figma’s WebAssembly canvas engine. Uses generative visual models to synthesize vector UI layouts, suggest layer naming hierarchies, and populate realistic contextual mock copy.',
    downloadsOrUsers: '4M+ Product Designers',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['Web', 'macOS', 'Windows', 'iPad'],
    category: 'Design',
    company: 'Figma',
    website: 'https://figma.com',
    pricing: ['Freemium'],
    avgRating: 4.42,
    totalRatings: 4180,
    totalReviews: 290,
    ratingDistribution: { 1: 240, 2: 480, 3: 1200, 4: 1360, 5: 900 },
    verified: true,
    founded: 2012,
    twitter: '@figma',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Added Visual Search for components and instant text translation inside design frames.',
    dataSafety: {
      encryption: 'SOC 2 Type II, ISO 27001, TLS 1.3; strict enterprise team isolation',
      training: 'Customers can disable AI training on private design files via admin settings',
      compliance: 'GDPR, CCPA, SOC 2 compliant',
      retention: 'Design file version history and assets managed per team retention policies',
    },
    screenshots: [
      { title: 'Generative UI Frames', caption: 'Describe an app screen and generate fully editable vector layouts with auto-layout' },
      { title: 'Visual Asset Search', caption: 'Find existing components and design system tokens matching any visual screenshot' },
      { title: 'Auto-Rename & Cleanup', caption: 'Organize messy layers into clean, semantic component hierarchies with one click' },
    ],
    features: [
      'Text-to-UI component and mock application layout generation',
      'Visual asset search matching art direction, color palettes, and icons',
      'Auto-naming layers and auto-generating realistic contextual text copy',
      'Instant background removal and smart image replacement',
    ],
    useCases: [
      'Drafting initial wireframe explorations and mobile app design variations',
      'Replacing placeholder lorem ipsum with realistic customer data and names',
      'Automating layer cleanup and component organization before handoff',
    ],
    pros: [
      'Zero context switching away from the Figma design canvas',
      'Outputs editable native Figma vectors, styles, and autolayouts',
      'Streamlines tedious repetitive prep work for design systems',
    ],
    cons: [
      'Generated components still require manual polish by experienced designers',
      'Limited custom design system token support during first-pass prompt generation',
    ],
  },
  {
    docId: 'grammarly.com',
    domain: 'grammarly.com',
    name: 'Grammarly',
    seoTitle: 'Grammarly: Free AI Writing Assistant & Grammar Checker',
    metaDescription: 'Write with confidence using Grammarly’s AI-powered writing assistant. Fix grammar, adjust tone, and polish your writing everywhere you type.',
    seoKeywords: ['grammarly', 'ai writing assistant', 'grammar checker', 'tone detector', 'plagiarism checker', 'proofreading'],
    howItWorks: 'Real-time natural language processing running unobtrusively across browser extensions, desktop apps, and mobile keyboards. Analyzes syntax, clarity, formality, and context to propose non-destructive edits and stylistic enhancements.',
    downloadsOrUsers: '30M+ Daily Users',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['Web', 'Chrome', 'Firefox', 'Safari', 'macOS', 'Windows', 'iOS', 'Android'],
    category: 'Copywriting',
    company: 'Grammarly',
    website: 'https://grammarly.com',
    pricing: ['Freemium'],
    avgRating: 4.69,
    totalRatings: 26800,
    totalReviews: 1640,
    ratingDistribution: { 1: 900, 2: 1900, 3: 5400, 4: 9800, 5: 8800 },
    verified: true,
    founded: 2009,
    twitter: '@Grammarly',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Added generative personalized voice profiles and team style guide compliance checkers.',
    dataSafety: {
      encryption: 'Enterprise grade TLS 1.3 and AES-256; text is never sold to third parties',
      training: 'User text is not used to train generative AI foundation models',
      compliance: 'SOC 2 Type II, ISO 27001, HIPAA, GDPR compliant',
      retention: 'Ephemeral processing by default; users can delete stored snippets anytime',
    },
    screenshots: [
      { title: 'Universal Floating Widget', caption: 'Real-time clarity suggestions and grammar corrections everywhere you type' },
      { title: 'Tone & Formality Meter', caption: 'Ensure your message sounds professional, direct, or friendly before sending' },
      { title: 'Generative Rewrites', caption: 'Instantly shorten, expand, or adjust the formality of existing paragraphs' },
    ],
    features: [
      'Universal browser and desktop application writing extension',
      'Real-time tone detector and clarity improvement recommendations',
      'Plagiarism checker with citations against billions of web pages',
      'Generative rewrite suggestions tailored to chosen formality levels',
    ],
    useCases: [
      'Polishing executive emails, sales proposals, and client correspondence',
      'Ensuring consistent brand voice across marketing and customer support teams',
      'Grammar proofreading and vocabulary enrichment for non-native English speakers',
    ],
    pros: [
      'Works seamlessly everywhere you type without disrupting your normal workflow',
      'Reliable grammar suggestions without making unwanted drastic rewrites',
      'Excellent organizational style guide enforcement for corporate teams',
    ],
    cons: [
      'Can be overly prescriptive or conservative on creative writing styles',
      'Premium subscription is relatively expensive for casual individual users',
    ],
  },
  {
    docId: 'gamma.app',
    domain: 'gamma.app',
    name: 'Gamma',
    seoTitle: 'Gamma: AI for Presentations, Webpages & Docs',
    metaDescription: 'Create beautiful presentations, webpages, and documents in seconds with Gamma’s AI-powered design generator.',
    seoKeywords: ['gamma ai', 'ai presentations', 'ai slide maker', 'pitch deck generator', 'interactive presentations', 'powerpoint ai'],
    howItWorks: 'Uses multimodal generative models to transform raw bulleted outlines or documents into modern, responsive card-based slide decks and web pages with flexible typography, palettes, and embedded interactive widgets.',
    downloadsOrUsers: '3M+ Presenters',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'San Francisco, CA, USA',
    platforms: ['Web'],
    category: 'Presentations',
    company: 'Gamma',
    website: 'https://gamma.app',
    pricing: ['Freemium'],
    avgRating: 4.65,
    totalRatings: 3260,
    totalReviews: 210,
    ratingDistribution: { 1: 120, 2: 220, 3: 700, 4: 1100, 5: 1120 },
    verified: true,
    founded: 2020,
    twitter: '@meetgamma',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Added PPTX export fidelity enhancements and live interactive embed cards.',
    dataSafety: {
      encryption: 'TLS 1.3 and AES-256 encrypted; private links and workspace permissions',
      training: 'User deck contents protected under terms of service',
      compliance: 'GDPR and SOC 2 compliant',
      retention: 'Export decks anytime as PDF or PPTX; full deck deletion supported',
    },
    screenshots: [
      { title: 'Prompt to Slide Deck', caption: 'Generate polished 10-slide decks from a brief outline in under a minute' },
      { title: 'Interactive Responsive Cards', caption: 'Flexible card layouts that break free from rigid 16:9 slide limitations' },
      { title: 'One-Click Restyling', caption: 'Swap fonts, colors, and layouts across your entire deck without manual nudging' },
    ],
    features: [
      'One-click prompt or document conversion to polished presentation decks',
      'Responsive interactive card layouts with embedded videos and live forms',
      'Restyle entire presentations instantly with curated palettes and typography',
      'Export seamlessly to PDF and editable PPTX PowerPoint formats',
    ],
    useCases: [
      'Fast turnaround on startup pitch decks and investor presentation briefs',
      'Internal company kickoffs, product roadmaps, and strategy update decks',
      'Conference lectures, educational lessons, and interactive workshop slides',
    ],
    pros: [
      'Saves hours of frustrating manual alignment compared to legacy PowerPoint',
      'Generates clean, modern editorial layouts that look professionally designed',
      'Supports shareable interactive web links with viewer analytics',
    ],
    cons: [
      'PowerPoint export fidelity can occasionally shift custom font kerning',
      'Free tier attaches a Gamma badge to exported presentations',
    ],
  },
  {
    docId: 'suno.com',
    domain: 'suno.com',
    name: 'Suno',
    seoTitle: 'Suno: Make a Song on Any Topic in Any Style',
    metaDescription: 'Generate full songs with realistic vocals, instruments, and complete arrangements from simple text prompts with Suno AI.',
    seoKeywords: ['suno ai', 'ai music generator', 'ai song maker', 'text to music', 'ai vocals', 'music production'],
    howItWorks: 'Deep audio diffusion models conditioned on genre tags, lyrical structures, and melodic harmonies. Synthesizes full 2 to 4 minute musical tracks including authentic vocals, instrumentation, and arrangement.',
    downloadsOrUsers: '12M+ Music Creators',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'Cambridge, MA, USA',
    platforms: ['Web', 'iOS'],
    category: 'Audio',
    company: 'Suno',
    website: 'https://suno.com',
    pricing: ['Freemium'],
    avgRating: 4.61,
    totalRatings: 6420,
    totalReviews: 410,
    ratingDistribution: { 1: 300, 2: 520, 3: 1400, 4: 2000, 5: 2200 },
    verified: true,
    founded: 2023,
    twitter: '@suno_ai_',
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Suno v3.5 launched with 4-minute full song generations and separated vocal/instrumental stems.',
    dataSafety: {
      encryption: 'TLS 1.3 transport encryption with secure cloud audio hosting',
      training: 'Trained on musical composition datasets; user custom lyrics remain private',
      compliance: 'Compliant with standard copyright licensing standards',
      retention: 'Users retain full ownership of songs created on paid subscription plans',
    },
    screenshots: [
      { title: 'Natural Language Song Generator', caption: 'Describe a mood, genre, or story and generate two distinct song variations' },
      { title: 'Custom Lyrics Mode', caption: 'Write your own verses and choruses with precise musical genre steering' },
      { title: 'Stem Separation & Audio Download', caption: 'Download high-fidelity MP3 and WAV stems for vocals and instruments' },
    ],
    features: [
      'Generates complete multi-minute songs with vocals, harmonies, and instruments',
      'Granular style prompt controls for musical genre, tempo, mood, and instrumentation',
      'Custom lyrics mode with song section markers ([Verse], [Chorus], [Guitar Solo])',
      'High-quality audio stem download and direct social media sharing links',
    ],
    useCases: [
      'Original background music scoring for YouTube creators, podcasts, and indie games',
      'Rapid musical prototyping, melody exploration, and songwriting inspiration',
      'Custom personalized birthday jingles, humorous songs, and celebration tracks',
    ],
    pros: [
      'Incredible vocal realism, emotional expression, and harmonic progression',
      'Simple natural language prompting produces catchy hooks in seconds',
      'Fast 30-second generation turnaround for 2 parallel audio options',
    ],
    cons: [
      'Fine-grained mixing and EQ mastering cannot be adjusted manually inside the app',
      'Commercial copyright usage rights require an active paid subscription plan',
    ],
  },
  {
    docId: 'newtool.example',
    domain: 'newtool.example',
    name: 'Draftsmith',
    seoTitle: 'Draftsmith: Technical Writing & Editorial AI Assistant',
    metaDescription: 'A long-form editing assistant for technical publications, research whitepapers, and engineering documentation.',
    seoKeywords: ['draftsmith', 'technical writing ai', 'editorial assistant', 'whitepaper editor', 'jargon simplifier'],
    howItWorks: 'Specialized language models trained on peer-reviewed literature and technical documentation. Evaluates readability metrics, detects passive voice, and clarifies complex engineering terminology.',
    downloadsOrUsers: '10K+ Beta Users',
    contentRating: 'Rated for Everyone (3+)',
    developerHQ: 'Austin, TX, USA',
    platforms: ['Web'],
    category: 'Copywriting',
    company: 'Draftsmith',
    website: 'https://newtool.example',
    pricing: ['Free'],
    avgRating: 0,
    totalRatings: 0,
    totalReviews: 0,
    ratingDistribution: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 },
    verified: false,
    founded: 2026,
    twitter: null,
    createdAt: null,
    updatedAt: null,
    whatsNew: 'Initial public beta release with paragraph restructuring and technical readability scoring.',
    dataSafety: {
      encryption: 'TLS 1.3 transport encryption',
      training: 'Zero retention and zero model training on customer drafts',
      compliance: 'GDPR compliant',
      retention: 'Documents deleted immediately upon closing the session',
    },
    screenshots: [
      { title: 'Technical Readability Scorer', caption: 'Calculates Flesch-Kincaid grade levels and highlights convoluted sentence structures' },
      { title: 'Paragraph Restructuring', caption: 'Reorganizes dense technical claims into clear, logical reader progressions' },
    ],
    features: [
      'Paragraph-by-paragraph restructuring suggestions for technical clarity',
      'Jargon highlighter and automated Flesch-Kincaid readability grading',
      'Grammar checking calibrated specifically to peer-reviewed technical publications',
    ],
    useCases: [
      'Editing technical documentation, API guides, and engineering whitepapers',
      'Simplifying academic jargon for general audience comprehension',
    ],
    pros: [
      'Completely free during the initial open beta period',
      'Uncluttered minimalist editing interface that keeps you focused on writing',
    ],
    cons: [
      'Early access product with evolving feature set',
      'Awaiting initial community ratings and user reviews',
    ],
  },
];

const day = 86_400_000;
const ago = (days) => new Date(Date.now() - days * day).toISOString();

export const MOCK_REVIEWS = [
  {
    id: 'r1',
    toolDomain: 'cursor.com',
    rating: 5,
    title: 'The first tool that understood our monorepo',
    body: 'We moved a 400-file service over to a new router and it held the whole dependency graph in view the entire time. The diff review step is what makes it trustworthy — nothing lands without me seeing it.',
    userName: 'Alex Rivera',
    userPhoto: '',
    likes: 24,
    createdAt: ago(1),
  },
  {
    id: 'r2',
    toolDomain: 'claude.ai',
    rating: 5,
    title: 'Holds a long argument together',
    body: 'I use it for contract review. It keeps track of definitions across sixty pages, which is exactly where the others start contradicting themselves.',
    userName: 'Dana Whitfield',
    userPhoto: '',
    likes: 18,
    createdAt: ago(2),
  },
  {
    id: 'r3',
    toolDomain: 'runwayml.com',
    rating: 3,
    title: 'Great shots, unpredictable cost',
    body: 'When it works the footage is genuinely usable. Getting there took far more credits than I budgeted, and there is no way to preview cheaply first.',
    userName: 'Sam Okafor',
    userPhoto: '',
    likes: 9,
    createdAt: ago(3),
  },
  {
    id: 'r4',
    toolDomain: 'midjourney.com',
    rating: 4,
    title: 'Unmatched for mood, awkward for briefs',
    body: 'Everything it makes is beautiful and about eighty percent of what I asked for. Fine for exploration, frustrating when a client has already approved a layout.',
    userName: 'Priya Nair',
    userPhoto: '',
    likes: 31,
    createdAt: ago(5),
  },
  {
    id: 'r5',
    toolDomain: 'notion.so',
    rating: 2,
    title: 'Summaries I have to check line by line',
    body: 'It confidently restated a decision our team never made. Convenient that it sits next to the docs, but I stopped trusting the output unattended.',
    userName: 'Tomas Weber',
    userPhoto: '',
    likes: 12,
    createdAt: ago(6),
  },
  {
    id: 'r6',
    toolDomain: 'elevenlabs.io',
    rating: 5,
    title: 'Narration our listeners cannot pick out',
    body: 'Twelve hours of audiobook, two rounds of notes. The pronunciation dictionary is what sold it — proper nouns stay correct across the whole run.',
    userName: 'Marta Lindqvist',
    userPhoto: '',
    likes: 15,
    createdAt: ago(8),
  },
  {
    id: 'r7',
    toolDomain: 'claude.ai',
    rating: 4,
    title: 'Careful, occasionally too careful',
    body: 'The writing quality is the best of the group. It does sometimes hedge on questions that had one clear answer, which means an extra round of prompting.',
    userName: 'Ibrahim Souza',
    userPhoto: '',
    likes: 7,
    createdAt: ago(11),
  },
  {
    id: 'r8',
    toolDomain: 'cursor.com',
    rating: 4,
    title: 'Worth it once you turn the noise down',
    body: 'Out of the box it suggests too much. After narrowing the rules file to our conventions it became the fastest way to work through a backlog of small fixes.',
    userName: 'Chen Wei',
    userPhoto: '',
    likes: 11,
    createdAt: ago(14),
  },
  {
    id: 'r9',
    toolDomain: 'chatgpt.com',
    rating: 5,
    title: 'The daily driver that handles almost everything',
    body: 'From debugging tricky SQL joins to drafting client proposals and summarizing research papers, GPT-4o has become essential. Advanced voice mode is shockingly natural when bouncing ideas around.',
    userName: 'Sarah Jenkins',
    userPhoto: '',
    likes: 42,
    createdAt: ago(2),
  },
  {
    id: 'r10',
    toolDomain: 'perplexity.ai',
    rating: 5,
    title: 'Replaced standard search engines for technical queries',
    body: 'Having verifiable footnote links for every single sentence makes research ten times faster. You never have to wonder if it hallucinated an API method because you can click directly to the docs.',
    userName: 'Marcus Vance',
    userPhoto: '',
    likes: 29,
    createdAt: ago(4),
  },
  {
    id: 'r11',
    toolDomain: 'v0.dev',
    rating: 5,
    title: 'Cut our frontend prototyping time by 80%',
    body: 'Generating clean Tailwind and shadcn components from natural language description is pure magic. We copy-paste the component into our Next.js app and wire the props in minutes.',
    userName: 'Elena Rostova',
    userPhoto: '',
    likes: 33,
    createdAt: ago(3),
  },
  {
    id: 'r12',
    toolDomain: 'github.com',
    rating: 4,
    title: 'Sub-second tab completion is hard to live without',
    body: 'It finishes repetitive patterns, boilerplate functions, and test cases before you even finish typing the function signature. Chat could be deeper on multi-file tasks, but the inline autocomplete is unmatched.',
    userName: 'David K.',
    userPhoto: '',
    likes: 19,
    createdAt: ago(7),
  },
];
